# Use an official PyTorch image with CUDA support as the base image
FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

# Install additional Python packages required by the script
RUN pip install numpy pandas fastparquet
